### ISSUE TITLE
segmentCPP question.

### ISSUE THREAD

**Issue by zhanhe18** [CSAILVision/LabelMeAnnotationTool#18]
I recently want to change some function of scribble , so I modified the source code , and make once , then I got example.js and example.js.mem two files , I put two files into annotationTool/js/folder . and then problem comes . I got a "you need to wait for the runtime to be ready (e.g. wait for main() to be called).) " error , But I know , it's some js code issues . May I ask you add something it to example.js after it be created ? If you not add something , you compile it as I did , how does it worked ? I readed the Emscripten FAQ but I am so stupid that to know what the document want to say and how to do , could you help me to fix that ? Thanks whatever .

**Comment by xavierpuigf** [comment]
Yes, the example.js file should be changed. More specifically, there is a line with the following piece of code memoryInitializer="example.js.mem" which should be changed to memoryInitializer="annotationTools/js/example.js.mem" so that the segmentation tool works with the files located in the correct folders (i.e annotationTools/js).
I will try to make this name change automatic with the makefile. Thanks for pointing it out!
